### ISSUE TITLE
i try encrypt a vhdx file,OverflowError

### ISSUE THREAD

**Issue by vinsonpyg** [jlinoff/lock_files#7]
the file size is 5.16GB,VERSION = '1.1.3'
C:\Users\vinso\Desktop\lock_files>lock_files.py -P vinson -vv  --lock D:\360Downloads\Software\
INFO:544 lock "D:\360Downloads\Software\vinson.vhdx" --> "D:\360Downloads\Software\vinson.vhdx.locked"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\vinso\Desktop\lock_files\lock_files.py", line 455, in thread_process_file
    process_file(opts, password, entry, stats)
  File "C:\Users\vinso\Desktop\lock_files\lock_files.py", line 588, in process_file
    lock_file(opts, password, path, stats)
  File "C:\Users\vinso\Desktop\lock_files\lock_files.py", line 548, in lock_file
    data = AESCipher(openssl=opts.openssl).encrypt(password, content)
  File "C:\Users\vinso\Desktop\lock_files\lock_files.py", line 187, in encrypt
    ciphertext_binary = encryptor.update(padded_plaintext) + encryptor.finalize()
  File "C:\Python27\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 149, in update
    return self._ctx.update(data)
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
**OverflowError: integer 5540675600 does not fit '32-bit int'**

**Comment by jlinoff** [comment]
Thank you for sending this. I have never tried to encrypt a single file that was that large. Because i originally designed this for source code and document archives. I will look into this as part of the work on handling large files.

Can you please provide the following information? That would really help me.

1. What OS/version are you using?
2. What version of python are you using?
3. How much RAM/virtual memory do you have?

**Comment by jlinoff** [comment]
I finally got back to this way, way too late but here is the simplest solution to this for anyone looking at this in the future:

No need to change `lock_files.py`, just use `tar`, `split` and `cat` with `lock_files`.  Here is a simple, UNTESTED example that shows the basic idea:

### Lock a huge file named /tmp/huge.dat
```shell
mkdir lock
cd lock
split -b 100m /tmp/huge.dat
lock_files.py -P secret *
tar cf /tmp/huge.dat.locked.tar *locked
```
### Unlock the files
```shell
mkdir unlock
cd unlock
tar xf /tmp/huge.dat.locked.tar
lock_files.py -P secret --unlock *
cat * >huge.dat
cmp /tmp/huge.dat huge.dat
```
